# Generated by Django 2.2.4 on 2019-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('project_title', models.CharField(max_length=20)),
                ('project_img1', models.ImageField(upload_to='photos/')),
                ('project_img2', models.ImageField(upload_to='photos/')),
                ('project_team', models.ImageField(upload_to='photos/')),
                ('project_description', models.TextField(blank=True)),
                ('circuit_design1', models.ImageField(blank=True, upload_to='photos/')),
                ('circuit_design2', models.ImageField(blank=True, upload_to='photos/')),
                ('circuit_design3', models.ImageField(blank=True, upload_to='photos/')),
                ('circuit_design4', models.ImageField(blank=True, upload_to='photos/')),
                ('des_spec1', models.TextField(blank=True)),
                ('des_spec2', models.TextField(blank=True)),
                ('des_spec3', models.TextField(blank=True)),
                ('des_spec4', models.TextField(blank=True)),
                ('des_spec5', models.TextField(blank=True)),
                ('youtube_vid', models.URLField(max_length=100)),
            ],
        ),
    ]
