# Generated by Django 2.2.4 on 2019-08-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=5)),
                ('post', models.CharField(max_length=10)),
                ('facebook_link', models.URLField(max_length=100)),
                ('github_link', models.URLField(max_length=100)),
                ('linkdein_link', models.URLField(max_length=100)),
            ],
        ),
    ]
