# Generated by Django 2.2.4 on 2019-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.ImageField(default=0, upload_to='photos/'),
            preserve_default=False,
        ),
    ]
