# Generated by Django 2.2.4 on 2019-08-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_team_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('small_des', models.TextField()),
                ('event_image', models.ImageField(upload_to='photos/')),
                ('big_des1', models.TextField()),
                ('big_des2', models.TextField()),
                ('big_des3', models.TextField()),
                ('event_image1', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
