# Generated by Django 2.2.4 on 2019-08-19 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_events'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
    ]
