# Generated by Django 2.2.4 on 2019-08-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20190819_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image10',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image2',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image3',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image4',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image5',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image6',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image7',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image8',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_image9',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image1',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
