# Generated by Django 2.2.4 on 2019-09-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20190822_1949'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
